spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.249/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.199.249
    port: 6379
server:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell/
#  level:
#    com.wsheng.LoggerTest: debug

wechat:
  mpAppId: wxed289aba651858c4
  mpAppSecret: e294bba01387e733b3177e98e3de749f
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1511264911
  mchKey: 930106086666wangshengxxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://shengge.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://shengge.natapp1.cc
  wechatOpenAuthorize: http://shengge.natapp1.cc
  sell: http://shengge.natapp1.cc